services:
  - type: worker
    name: bookmyshow-monitor
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: CHECK_INTERVAL
        value: "30"
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: FAST2SMS_API_KEY
        sync: false
      - key: FAST2SMS_NUMBER
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_CALL_FROM
        sync: false
      - key: PHONE_CALL_TO
        sync: false
      - key: NTFY_TOPIC
        sync: false
      - key: NTFY_TOKEN
        sync: false
